### ISSUE TITLE
Postman collection to check test resources

### ISSUE THREAD

**Issue by manedev79** [JanLoebel/simplest-mock-server#2]
Hi Jan,
I thought about having a [Postman](https://www.getpostman.com/) collection to check the test resources which are there by default in the config.json. One could run the whole collection as a smoke test when changing the mock server.
Let me know what you think about that.

**Comment by JanLoebel** [comment]
Yes sounds like a great idea! Do you know if there is some tool which uses a postman collection and runs that automatically against a server so we could start with the Postman collection and manual smoke tests and automate it afterward with the same collection?

**Comment by manedev79** [comment]
Glad that you like it. There is [newman](https://www.getpostman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman) which allows you to run Postman collections via command line. It is also suitable for CI/CD integration.

I can provide a PR with a Postman collection and we extend that with newman before we merge.

**Comment by JanLoebel** [comment]
@manedev79 Thanks again for your contributions! Last step was to integrate it in any CI (used Travis-CI here) to run the tests on each commit.
